services:
  mysql-db:
    image: mysql:8.0
    container_name: desafio-ustore
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: desafio_ustore
    ports:
      - '3406:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  nest-app:
    build: .
    ports:
      - '4000:3000'
    depends_on:
      - mysql-db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod

volumes:
  mysql_data:
